version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "80:80"
    links:
      - db
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
    volumes:
     - /data/webshop/config:/var/www/html/app/etc
     - /data/webshop/media:/var/www/html/pub/media
  db:
    image: mysql:5.6.23
    volumes:
      - /data/webshop/db:/var/lib/mysql/data
    env_file:
      - .env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: '10m'
        max-file: '5'


